run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - gocritic
    - revive

linters-settings:
  govet:
    enable:
      - shadow
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - exitAfterDefer  # CLI apps often exit after defer
      - rangeValCopy    # Sometimes acceptable for readability

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: llm-shared/
      linters:
        - gocritic
        - revive